name: CI

on: [push, pull_request]

jobs:
  linux-test:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        emacs-version: [25.1, 25.2, 25.3, 26.1, 26.2, 26.3, 27.1, 27.2]
        experimental: [false]
        include:
          - emacs-version: snapshot
            experimental: true

    steps:
      - name: setenv
        run: echo "ACTIONS_ALLOW_UNSECURE_COMMANDS=true" >> $GITHUB_ENV

      - uses: actions/checkout@v1

      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs-version }}

      - name: Test
        run: |
          rm -rf ~/.emacs.d; \
          mv -f ~/work/.emacs.d/.emacs.d ~; \
          mkdir -p ~/.emacs.d/elpa/gnupg && gpg --homedir ~/.emacs.d/elpa/gnupg --receive-keys 066DAFCB81E42C40; \
          emacs --version; \
          emacs -q --batch \
          --eval "(message \"Testing...\")" \
          --eval "(when (and (require 'org nil t) (string= (org-version) \"\"))
                     (advice-add 'org-version :override (lambda (&rest _) \"9.3\")))" \
          --eval "(let ((package-check-signature nil)
                        (early-init-file (locate-user-emacs-file \"early-init.el\"))
                        (user-init-file (locate-user-emacs-file \"init.el\")))
                    (and (>= emacs-major-version 27) (load early-init-file))
                    (load user-init-file)
                    (run-hooks 'after-init-hook)
                    (run-hooks 'emacs-startup-hook)
                    (run-hooks 'window-setup-hook))" \
          --eval "(message \"Testing...done\")"
